apis:
  filter:
    root: ../dist/merged-woosmap-openapi3.json
    decorators:
      filter-in:
        property: operationId
        value:
          - localitiesAutocomplete
          - localitiesDetails
          - localitiesGeocode
          - storeSearch
          - getDistanceMatrix
      plugin/trim-description:
        maxParameterDescriptionLength: 690
        maxOperationDescriptionLength: 290
      plugin/one-security-scheme:
        securitySchemeName: PrivateApiKeyHeaderAuth
      plugin/remove-parameters:
        parameters:
          - x-codeSamples
          - example
          - examples
          - 401
          - 403
          - 429
      plugin/remove-unused-tags: on
plugins:
  - ./decorators.js
rules:
  no-unresolved-refs: error
  no-unused-components: error
  security-defined: error
  spec: error
  spec-components-invalid-map-name: error
