name: routing
in: query
example: "fastest"
schema:
  type: string
  enum:
    - fastest
    - shortest
description: >
  Specifies what to base the cost calculation on. If not specified default is `fastest`.
    * `fastest` will include traffic and optimise the route based on the smallest travel time.
    * `shortest` will optimise based on travel distance.
