name: Build and Test
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.9
      - name: Install dependencies
        run: |
          pnpm i -F
      - run: pnpm run build -- --profile /tmp/bazel-profile-build.gz --jobs 8
      - run: pnpm test -- --jobs 8
      - name: Upload Bazel profiles
        uses: actions/upload-artifact@v4
        with:
          name: bazel profiles
          path: |
            /tmp/bazel-profile-*.gz
