name: Build and Test
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.9
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - run: pnpm run build
      - run: pnpm test