name: Build and Test
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build -- --profile /tmp/bazel-profile-build.gz --jobs 8
        env:
          GH_TOKEN: ${{ secrets.WOOSMAP_GH_ACCESS_TOKEN }}
      - run: npm test -- --jobs 8
        env:
          GH_TOKEN: ${{ secrets.WOOSMAP_GH_ACCESS_TOKEN }}
      - name: Upload Bazel profiles
        uses: actions/upload-artifact@v2
        with:
          name: bazel profiles
          path: |
            /tmp/bazel-profile-*.gz
