name: Update dist
on:
  repository_dispatch:
    types: [update-dist-command]
jobs:
  update-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.WOOSMAP_GH_ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - run: npm ci
      - name: Update dist
        run: |
          npm run build
          git config --global user.name 'gaelsimon'
          git config --global user.email 'gael.simon@woosmap.com'
          git add dist
          git commit -m "chore: update dist folder [skip ci]" || true
          git push origin
        env:
          GH_TOKEN: ${{ secrets.WOOSMAP_GH_ACCESS_TOKEN }}
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.WOOSMAP_GH_ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: rocket
