# On release, send update-openapi event to woosmap/developers.woosmap.com repository
name: Update DevDoc
on:
  release:
    types: [ published ]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Release Event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.WOOSMAP_GH_ACCESS_TOKEN }}
          repository: woosmap/developers.woosmap.com
          event-type: update_openapi
          client-payload: '{"release_name": "${{ github.event.release.tag_name }}", "source_url":  "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.event.release.tag_name }}.tar.gz", "openapi_spec_url": "${{ github.server_url }}/${{ github.repository }}/releases/latest/download/woosmap-openapi3.json"}'


